package: qanda
version: '2.0.11'
author: 'Alexander Walther'
supportpage: https://alexplusde.github.io/qanda/
load: late

requires:
    php:
        version: '>7.4,<9'
    redaxo: ^5.12
    packages:
        yform: '>=4.0,<5'

page:
    title: translate:qanda
    prio: 100
    icon: rex-icon fa-question-circle

pages:
    qanda:
        title: translate:qanda
        main: true
        block: system
        prio: 16
        icon: rex-icon fa-question-circle
        perm: qanda[]
        subpages: 
            qanda:
                title: Fragen und Antworten
                icon: rex-icon fa-question-circle
                subPath: pages/data_edit.php
                itemattr:
                    table_name: rex_qanda
                perm: qanda[qanda]
            category:
                title: Kategorien
                icon: rex-icon fa-folder
                subPath: pages/data_edit.php
                itemattr:
                    table_name: rex_qanda_category
                perm: qanda[category]
            settings:
                title: Einstellungen
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            docs:
                title: Hilfe
                subPath: README.md
                icon: rex-icon fa-info-circle
                itemclass: pull-right
                perm: qanda[docs]

default_config:
    editor: 'class="form-control cke5-editor" data-lang="de" data-profile="default"'
