theme: jekyll-theme-minimal
title: FAQ für REDAXO 5
description: Fragen und Antworten für REDAXO 5 auf YForm-Basis 
logo: https://raw.githubusercontent.com/alexplusde/qanda/master/docs/screenshot.png
show_downloads: true
